const productList = [
    {
        id: 1,
        Publisher:"EUP",
        MonthYear:"Jan 2023",
        OverallPerformance:98,
        Schedule: 87,
        Quality: 90,
        Communication:  89,
        CustomerSatisfaction:92,
        AccountManagement: 95,
        RFT:2,
        PublicationSpeed:  19,
        PE:2,
        CE:1,
        Typesetting:2,
        ProjectManagement:1,
    }, {
        id: 2,
        Publisher:"IWAP",
        MonthYear:"Jan 2023",
        OverallPerformance:98,
        Schedule: 87,
        Quality: 90,
        Communication:  89,
        CustomerSatisfaction:92,
        AccountManagement: 95,
        RFT:2,
        PublicationSpeed:  19,
        PE:2,
        CE:1,
        Typesetting:2,
        ProjectManagement:1,
    }, {
        id: 3,
        Publisher:"IWAP",
        MonthYear:"Jan 2023",
        OverallPerformance:98,
        Schedule: 87,
        Quality: 90,
        Communication:  89,
        CustomerSatisfaction:92,
        AccountManagement: 95,
        RFT:2,
        PublicationSpeed:  19,
        PE:2,
        CE:1,
        Typesetting:2,
        ProjectManagement:1,
    }, {
        id: 4,
        Publisher:"IWAP",
        MonthYear:"Jan 2023",
        OverallPerformance:98,
        Schedule: 87,
        Quality: 90,
        Communication:  89,
        CustomerSatisfaction:92,
        AccountManagement: 95,
        RFT:2,
        PublicationSpeed:  19,
        PE:2,
        CE:1,
        Typesetting:2,
        ProjectManagement:1,
    }, {
        id: 5,
        Publisher:"IWAP",
        MonthYear:"Jan 2023",
        OverallPerformance:98,
        Schedule: 87,
        Quality: 90,
        Communication:  89,
        CustomerSatisfaction:92,
        AccountManagement: 95,
        RFT:2,
        PublicationSpeed:  19,
        PE:2,
        CE:1,
        Typesetting:2,
        ProjectManagement:1,
    }, {
        id: 6,
        Publisher:"IWAP",
        MonthYear:"Jan 2023",
        OverallPerformance:98,
        Schedule: 87,
        Quality: 90,
        Communication:  89,
        CustomerSatisfaction:92,
        AccountManagement: 95,
        RFT:2,
        PublicationSpeed:  19,
        PE:2,
        CE:1,
        Typesetting:2,
        ProjectManagement:1,
    }, {
        id: 7,
        Publisher:"IWAP",
        MonthYear:"Jan 2023",
        OverallPerformance:98,
        Schedule: 87,
        Quality: 90,
        Communication:  89,
        CustomerSatisfaction:92,
        AccountManagement: 95,
        RFT:2,
        PublicationSpeed:  19,
        PE:2,
        CE:1,
        Typesetting:2,
        ProjectManagement:1,
    }, {
        id: 8,
        Publisher:"IWAP",
        MonthYear:"Jan 2023",
        OverallPerformance:98,
        Schedule: 87,
        Quality: 90,
        Communication:  89,
        CustomerSatisfaction:92,
        AccountManagement: 95,
        RFT:2,
        PublicationSpeed:  19,
        PE:2,
        CE:1,
        Typesetting:2,
        ProjectManagement:1,
    }, {
        id: 9,
        Publisher:"IWAP",
        MonthYear:"Jan 2023",
        OverallPerformance:98,
        Schedule: 87,
        Quality: 90,
        Communication:  89,
        CustomerSatisfaction:92,
        AccountManagement: 95,
        RFT:2,
        PublicationSpeed:  19,
        PE:2,
        CE:1,
        Typesetting:2,
        ProjectManagement:1,
    }, {
        id: 10,
        Publisher:"IWAP",
        MonthYear:"Jan 2023",
        OverallPerformance:98,
        Schedule: 87,
        Quality: 90,
        Communication:  89,
        CustomerSatisfaction:92,
        AccountManagement: 95,
        RFT:2,
        PublicationSpeed:  19,
        PE:2,
        CE:1,
        Typesetting:2,
        ProjectManagement:1,
    }, {
        id: 11,
        Publisher:"IWAP",
        MonthYear:"Jan 2023",
        OverallPerformance:98,
        Schedule: 87,
        Quality: 90,
        Communication:  89,
        CustomerSatisfaction:92,
        AccountManagement: 95,
        RFT:2,
        PublicationSpeed:  19,
        PE:2,
        CE:1,
        Typesetting:2,
        ProjectManagement:1,
    }, {
        id: 12,
        Publisher:"IWAP",
        MonthYear:"Jan 2023",
        OverallPerformance:98,
        Schedule: 87,
        Quality: 90,
        Communication:  89,
        CustomerSatisfaction:92,
        AccountManagement: 95,
        RFT:2,
        PublicationSpeed:  19,
        PE:2,
        CE:1,
        Typesetting:2,
        ProjectManagement:1,
    }, {
        id: 13,
        Publisher:"IWAP",
        MonthYear:"Jan 2023",
        OverallPerformance:98,
        Schedule: 87,
        Quality: 90,
        Communication:  89,
        CustomerSatisfaction:92,
        AccountManagement: 95,
        RFT:2,
        PublicationSpeed:  19,
        PE:2,
        CE:1,
        Typesetting:2,
        ProjectManagement:1,
    }, {
        id: 14,
        Publisher:"IWAP",
        MonthYear:"Jan 2023",
        OverallPerformance:98,
        Schedule: 87,
        Quality: 90,
        Communication:  89,
        CustomerSatisfaction:92,
        AccountManagement: 95,
        RFT:2,
        PublicationSpeed:  19,
        PE:2,
        CE:1,
        Typesetting:2,
        ProjectManagement:1,
    }
]

export { productList }